<?php
declare(strict_types=1);

/**
 * Build an idempotent HRMS position seed from DBM IOS Volume II table text.
 *
 * Source: Department of Budget and Management, Index of Occupational
 * Services, Occupational Groups, Classes and Salary Grades, Volume II.
 * Extract the PDF using: pdftotext -table source.pdf source.txt
 *
 * Usage:
 *   php scripts/build_government_positions_seed.php source.txt output.sql
 */

if ($argc !== 3) {
    fwrite(STDERR, "Usage: php scripts/build_government_positions_seed.php <source.txt> <output.sql>\n");
    exit(1);
}

[$script, $sourcePath, $outputPath] = $argv;
$lines = file($sourcePath, FILE_IGNORE_NEW_LINES);
if ($lines === false) {
    throw new RuntimeException("Unable to read {$sourcePath}");
}

$positions = [];
$pattern = '/^\s*(.+?)\s+(\d{1,2})\s+(\d{2}-[A-Z]{2})\s+([A-Za-z0-9]+)\s+([A-Za-z0-9]+)\s*$/u';

foreach ($lines as $line) {
    if (!preg_match($pattern, $line, $matches)) {
        continue;
    }

    $title = trim($matches[1]);
    $title = str_replace(['!', 'Advertisinq'], ['I', 'Advertising'], $title);
    $title = preg_replace('/([a-z])([IV]+)(?=(?:\s+[ab8])?$)/u', '$1 $2', $title);
    $title = preg_replace('/\bUI\b/u', 'III', $title);
    $title = preg_replace('/\s+[ab8]\s*$/u', '', $title);
    $title = preg_replace('/\s+/u', ' ', $title);
    $title = str_replace([' I V', ' I II', ' I I'], [' IV', ' III', ' II'], $title);
    $title = trim($title, " \t\n\r\0\x0B.");

    $salaryGrade = (int) $matches[2];
    if ($title === '' || mb_strlen($title) > 150 || $salaryGrade < 1 || $salaryGrade > 33) {
        continue;
    }

    $key = mb_strtolower($title);
    $positions[$key] ??= ['title' => $title, 'salary_grade' => $salaryGrade];
}

// DBM-DepEd Joint Circular No. 01, s. 2025 additions and current allocations.
// These position classes postdate the base IOS Volume II source.
$educationCareerProgression = [
    'Teacher I' => 11, 'Teacher II' => 12, 'Teacher III' => 13,
    'Teacher IV' => 14, 'Teacher V' => 15, 'Teacher VI' => 16, 'Teacher VII' => 17,
    'Master Teacher I' => 18, 'Master Teacher II' => 19, 'Master Teacher III' => 20,
    'Master Teacher IV' => 21, 'Master Teacher V' => 22,
    'School Principal I' => 19, 'School Principal II' => 20,
    'School Principal III' => 21, 'School Principal IV' => 22,
];
foreach ($educationCareerProgression as $title => $salaryGrade) {
    $positions[mb_strtolower($title)] = ['title' => $title, 'salary_grade' => $salaryGrade];
}

ksort($positions, SORT_NATURAL | SORT_FLAG_CASE);

if (count($positions) < 2000) {
    throw new RuntimeException('Extraction validation failed: fewer than 2,000 unique positions found.');
}

foreach (['accountant i', 'administrative aide i', 'engineer i', 'teacher i', 'medical officer i'] as $required) {
    if (!isset($positions[$required])) {
        throw new RuntimeException("Extraction validation failed: missing {$required}.");
    }
}

$escape = static fn(string $value): string => str_replace("'", "''", $value);
$sql = "-- Philippine government position catalog\n"
    . "-- Source: DBM Index of Occupational Services, Occupational Groups, Classes and Salary Grades, Volume II.\n"
    . "-- Generated by scripts/build_government_positions_seed.php; safe to run repeatedly.\n\n"
    . "SET NAMES utf8mb4;\n"
    . "START TRANSACTION;\n\n"
    . "CREATE TEMPORARY TABLE government_position_seed (\n"
    . "    title VARCHAR(150) NOT NULL PRIMARY KEY,\n"
    . "    salary_grade VARCHAR(10) NOT NULL\n"
    . ") ENGINE=InnoDB;\n\n";

foreach (array_chunk(array_values($positions), 400) as $chunk) {
    $values = array_map(
        static fn(array $position): string => "('" . $escape($position['title']) . "', 'SG-" . $position['salary_grade'] . "')",
        $chunk
    );
    $sql .= "INSERT INTO government_position_seed (title, salary_grade) VALUES\n    "
        . implode(",\n    ", $values) . ";\n\n";
}

$sql .= "INSERT INTO positions (title, salary_grade)\n"
    . "SELECT seed.title, seed.salary_grade\n"
    . "FROM government_position_seed seed\n"
    . "LEFT JOIN positions existing ON LOWER(TRIM(existing.title)) = LOWER(TRIM(seed.title))\n"
    . "WHERE existing.id IS NULL;\n\n"
    . "DROP TEMPORARY TABLE government_position_seed;\n"
    . "COMMIT;\n";

if (file_put_contents($outputPath, $sql) === false) {
    throw new RuntimeException("Unable to write {$outputPath}");
}

fwrite(STDOUT, 'Generated ' . count($positions) . " unique government positions in {$outputPath}.\n");
