<?php require MODULES_PATH . '/shared/views/header.php'; ?>
<section class="ai-page aura-refresh" aria-labelledby="aura-title">
    <section class="ai-shell">
        <header class="aura-topbar"><a href="<?= BASE_URL ?>/dashboard">&larr; Workspace</a><span class="ai-status" id="aura-status" role="status">Ready to help</span></header>
        <div class="ai-heading">
            <span class="ai-orb" aria-hidden="true"><span>✦</span></span>
            <div><span class="launcher-eyebrow">Meet AURA</span><h1 id="aura-title">A little help. A lot of possibility.</h1><p>Your Administrative Utility and Records Assistant.<br>Explore ideas, find clarity, and move your work forward.</p></div>
        </div>
        <div class="ai-welcome"><strong>A good place to start</strong><div class="ai-prompts">
            <button type="button" data-prompt="How many employees are active?"><span aria-hidden="true">&#9678;</span><strong>Know your team</strong><small>Explore employee records</small></button>
            <button type="button" data-prompt="Summarize my pending tasks"><span aria-hidden="true">&#10003;</span><strong>Plan your next step</strong><small>Review your pending tasks</small></button>
            <button type="button" data-prompt="Explain the accomplishment workflow"><span aria-hidden="true">&#10023;</span><strong>Make progress</strong><small>Understand accomplishments</small></button>
        </div></div>
        <div class="aura-conversation-label">Your conversation</div>
        <div class="ai-messages" id="ai-messages" role="log" aria-label="Conversation with AURA" aria-live="polite" aria-relevant="additions text"><div class="ai-message ai-message-bot"><span class="ai-message-avatar" aria-hidden="true">✦</span><div>Hello! I’m AURA. What can I help you with today?</div></div></div>
        <div class="aura-composer"><form class="ai-form" id="ai-form">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Auth::csrfToken()) ?>">
            <input id="ai-input" name="message" maxlength="4000" placeholder="Ask AURA anything…" aria-label="Message AURA" autocomplete="off">
            <button class="ai-send" type="submit" aria-label="Send message"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 19V5m-6 6 6-6 6 6"/></svg></button>
        </form><small class="ai-note">AI can make mistakes. Verify important HR records.</small></div>
    </section>
</section>
<script>const aiForm=document.getElementById('ai-form'),aiInput=document.getElementById('ai-input'),aiMessages=document.getElementById('ai-messages'),aiHistory=[];document.querySelectorAll('.ai-prompts button').forEach(b=>b.addEventListener('click',()=>{aiInput.value=b.dataset.prompt;aiInput.focus()}));aiForm.addEventListener('submit',async e=>{e.preventDefault();const text=aiInput.value.trim();if(!text||aiForm.dataset.busy==='true')return;aiForm.dataset.busy='true';aiForm.querySelector('button').disabled=true;document.querySelector('.aura-refresh').classList.add('is-thinking');document.getElementById('aura-status').textContent='Thinking…';const formData=new FormData(e.target);formData.set('history',JSON.stringify(aiHistory));aiHistory.push({role:'user',content:text});aiMessages.insertAdjacentHTML('beforeend',`<div class="ai-message ai-message-user"><div>${text.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}</div></div>`);aiInput.value='';const wait=document.createElement('div');wait.className='ai-message ai-message-bot';wait.innerHTML='<span class="ai-message-avatar">✦</span><div>Thinking…</div>';aiMessages.appendChild(wait);aiMessages.scrollTop=aiMessages.scrollHeight;try{const r=await fetch(`${window.BASE_URL}/ai/chat`,{method:'POST',body:formData,headers:{Accept:'application/json'}}),j=await r.json();const reply=j.success?j.reply:(j.error||'Unable to get a response.');wait.querySelector('div').textContent=reply;aiHistory.push({role:'assistant',content:reply})}catch(_){wait.querySelector('div').textContent='Unable to connect to the AI service.'}finally{aiForm.dataset.busy='false';aiForm.querySelector('button').disabled=false;document.querySelector('.aura-refresh').classList.remove('is-thinking');document.getElementById('aura-status').textContent='Ready to help';}aiMessages.scrollTop=aiMessages.scrollHeight});</script>
<script>(()=>{const box=document.getElementById('ai-messages');const render=el=>{const text=el.textContent||'';if(!text.includes('|'))return;const rows=text.split('\n').filter(x=>x.trim().startsWith('|')&&!/^\s*\|?\s*:?-+/.test(x));if(rows.length<2)return;const grid=document.createElement('div');grid.className='ai-data-cards';rows.slice(0,8).forEach(row=>{const cells=row.split('|').map(x=>x.trim()).filter(Boolean);if(cells.length>=2){const card=document.createElement('div');card.className='ai-data-card';const title=document.createElement('strong');title.textContent=cells[0].replace(/\*\*/g,'');const detail=document.createElement('span');detail.textContent=cells.slice(1).join(' · ').replace(/<br\s*\/?>(\s*)/gi,' ');card.append(title,detail);grid.append(card)}});if(grid.children.length){el.replaceChildren(grid);const actions=document.createElement('div');actions.className='ai-actions';[['Open tasks','/tasks'],['View accomplishments','/accomplishments'],['Open analytics','/admin/dashboard']].forEach(([label,url])=>{if(text.toLowerCase().includes(label.split(' ')[1])){const a=document.createElement('a');a.href=window.BASE_URL+url;a.textContent=label;actions.append(a)}});if(actions.children.length)el.append(actions)}};new MutationObserver(()=>box.querySelectorAll('.ai-message-bot > div').forEach(render)).observe(box,{childList:true,subtree:true});})();</script>
<script>(()=>{const input=document.getElementById('ai-input');if(!input)return;const palettes={ocean:['#3b6fe0','#8b5cf6'],violet:['#7c3aed','#ec4899'],emerald:['#059669','#22c55e'],sunset:['#ea580c','#e11d48'],rose:['#e11d48','#a855f7'],teal:['#0891b2','#14b8a6']};const moods={mist:'#f7f4f1',lavender:'#f3f0fa',blush:'#fff2f4',mint:'#eef8f4',sky:'#eff6fc',sand:'#faf5e9',peach:'#fff0e6',rose:'#fff0f5',aqua:'#e8f8f8',lilac:'#f2edff',lemon:'#fffbe6',slate:'#e9eef5'};document.getElementById('ai-form').addEventListener('submit',()=>{const q=input.value.toLowerCase(),s={...JSON.parse(localStorage.getItem('hrms-appearance')||'{}')};let changed=false;if(/\b(dark|night)\b/.test(q)){s.mode='dark';changed=true}else if(/\b(light|bright)\b/.test(q)){s.mode='light';changed=true}else if(/\bsystem\b/.test(q)){s.mode='system';changed=true}for(const [name,colors] of Object.entries(palettes))if(q.includes(name)){s.palette=name;s.primary=colors[0];s.secondary=colors[1];changed=true}for(const [name,color] of Object.entries(moods))if(q.includes(name)){s.background=name;document.documentElement.style.setProperty('--mood-color',color);changed=true}if(changed){localStorage.setItem('hrms-appearance',JSON.stringify({...s,mode:s.mode||'system',palette:s.palette||'ocean',primary:s.primary||'#3b6fe0',secondary:s.secondary||'#8b5cf6',background:s.background||'mist'}));const dark=s.mode==='dark'||(s.mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.style.setProperty('--accent-blue',s.primary);document.documentElement.style.setProperty('--accent-violet',s.secondary);document.documentElement.style.setProperty('--accent-primary',s.primary);if(dark)document.documentElement.style.removeProperty('--bg-base');else document.documentElement.style.setProperty('--bg-base',moods[s.background]||moods.mist)}})})();</script>

<?php require MODULES_PATH . '/shared/views/footer.php'; ?>
